spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testDI
  mvc:
    throw-exception-if-no-handler-found: true

logging.level:
  ROOT: INFO
  org.springframework: INFO
