server:
  port: 8083

ms:
  host: localhost
  port: 8081
  client:
    name: database1

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testDI

logging.level:
  ROOT: INFO
  org.springframework: INFO
